package com.annguyenhoang.fashiongallery.model

import com.annguyenhoang.fashiongallery.R
import com.annguyenhoang.fashiongallery.enums.BookStatus
import com.annguyenhoang.fashiongallery.enums.LGBookType
import com.annguyenhoang.fashiongallery.enums.LGContentType

class Book(
    val id: Int? = null, // having on model api "id"
    val bookUuid: String, // having on model api "uuid"
    val bookType: LGBookType? = null, // have on model api "book_type"
    val thumbnail: Int = R.drawable.img_book, // have on model api "thumbnail"
    val name: String? = null, // having on model api "name"
    val category: List<LGCategory>? = null,
    val contentType: LGContentType? = null,
    val status: BookStatus? = null,
    val duration: Long? = null,
    val listeningTime: Long? = null,
    val readingTime: Long? = null,
    val totalOfViews: Int? = null, // having on model api "total_reads"
    val bestSentence: String? = null, // having on model api "quote"
    val avgRating: Float? = null,
    val totalOfRates: Int? = null, // having on model api "total_rates"
    val mostRecentAccess: Long? = null,
    val author: String = "Tô Hoài", // having on model api "author"
    val totalOfLikes: Int? = null,
    val publish: String? = null,
//    val publish: LocalDateTime? = null,
    val isSeries: Boolean? = null,
    val classId: Int? = null,
) {
    companion object {
        fun mock() =
            listOf(
                Book(
                    id = 1,
                    bookUuid = "4810dcde-fc06-456e-96fc-5859718d9d5d",
                    bookType = LGBookType.WORD_BOOK,
                    name = "K1Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(3),
                    contentType = LGContentType.WORD_BOOK,
                    status = BookStatus.IN_PROGRESS,
                    duration = 523,
                    readingTime = 233,
                    totalOfViews = 123,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 2.1f,
                    totalOfRates = 54,
                    mostRecentAccess = 1683823046,
                    totalOfLikes = 30,
                    publish = "2023-12-25 16:00:07", // LocalDateTime.of(2023, 12, 25, 16, 0,7),
                    classId = 1
                ),
                Book(
                    id = 2,
                    bookUuid = "4810dcde-fc06-456e-96fc-5859718d9d5d",
                    bookType = LGBookType.WORD_BOOK,
                    name = "Q2Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(6),
                    contentType = LGContentType.WORD_BOOK,
                    status = BookStatus.IN_PROGRESS,
                    duration = 112,
                    readingTime = 34,
                    totalOfViews = 0,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 4.6f,
                    totalOfRates = 1,
                    mostRecentAccess = 1698501107,
                    totalOfLikes = 421,
                    publish = "2023-12-25 16:00:07", // LocalDateTime.of(2023, 12, 25, 16, 0,7),
                    classId = 1
                ),
                Book(
                    id = 3,
                    bookUuid = "4810dcde-fc06-456e-96fc-5859718d9d5d",
                    bookType = LGBookType.WORD_BOOK,
                    name = "P3Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(8),
                    contentType = LGContentType.WORD_BOOK,
                    status = BookStatus.UNREAD,
                    duration = 445,
                    readingTime = 231,
                    totalOfViews = 345,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 4.5f,
                    totalOfRates = 421,
                    totalOfLikes = 122,
                    publish = "2023-10-12 16:00:07", // LocalDateTime.of(2023, 10, 12, 16, 0,7),
                    classId = 2
                ),
                Book(
                    id = 4,
                    bookUuid = "4810dcde-fc06-456e-96fc-5859718d9d5d",
                    bookType = LGBookType.WORD_BOOK,
                    name = "M4Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(2),
                    contentType = LGContentType.WORD_BOOK,
                    status = BookStatus.UNREAD,
                    duration = 32,
                    totalOfViews = 456,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 3.8f,
                    totalOfRates = 157,
                    totalOfLikes = 0,
                    publish = "2023-12-10 16:00:07", // LocalDateTime.of(2023, 12, 10, 16, 0,7),
                    classId = 3
                ),
                Book(
                    id = 5,
                    bookUuid = "4810dcde-fc06-456e-96fc-5859718d9d5d",
                    bookType = LGBookType.WORD_BOOK,
                    name = "N5Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(9),
                    contentType = LGContentType.WORD_BOOK,
                    status = BookStatus.FINISH,
                    duration = 322,
                    totalOfViews = 567,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 3.7f,
                    totalOfRates = 342,
                    totalOfLikes = 3032,
                    publish = "2023-12-12 16:20:07", // LocalDateTime.of(2023, 12, 12, 16, 20,7),
                    classId = 3
                ),
                Book(
                    id = 6,
                    bookUuid = "d24838dd-889a-4710-91d9-c6c3a20c2b0e",
                    bookType = LGBookType.AUDIO_BOOK,
                    name = "W6Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(7),
                    contentType = LGContentType.AUDIO_BOOK,
                    status = BookStatus.IN_PROGRESS,
                    duration = 3600,
                    listeningTime = 123,
                    totalOfViews = 678,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 3.1f,
                    totalOfRates = 123,
                    mostRecentAccess = 1689402873,
                    publish = "2023-02-12 16:00:07", // LocalDateTime.of(2023, 2, 12, 16, 0,7),
                    classId = 1
                ),
                Book(
                    id = 7,
                    bookUuid = "d24838dd-889a-4710-91d9-c6c3a20c2b0e",
                    bookType = LGBookType.AUDIO_BOOK,
                    name = "Z7Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(5),
                    contentType = LGContentType.AUDIO_BOOK,
                    status = BookStatus.IN_PROGRESS,
                    duration = 53423,
                    listeningTime = 3221,
                    totalOfViews = 789,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 4.1f,
                    totalOfRates = 322,
                    mostRecentAccess = 1675322607,
                    totalOfLikes = 3032,
                    publish = "2023-02-12 16:50:07", // LocalDateTime.of(2023, 2, 12, 16, 50,7),
                    classId = 2
                ),
                Book(
                    id = 8,
                    bookUuid = "d24838dd-889a-4710-91d9-c6c3a20c2b0e",
                    bookType = LGBookType.AUDIO_BOOK,
                    name = "H8Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(8),
                    contentType = LGContentType.AUDIO_BOOK,
                    status = BookStatus.UNREAD,
                    duration = 42213,
                    totalOfViews = 890,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 4.2f,
                    totalOfRates = 64,
                    totalOfLikes = 542,
                    publish = "2023-02-22 16:00:07", // LocalDateTime.of(2023, 2, 22, 16, 0,7),
                    classId = 4
                ),
                Book(
                    id = 9,
                    bookUuid = "d24838dd-889a-4710-91d9-c6c3a20c2b0e",
                    bookType = LGBookType.AUDIO_BOOK,
                    name = "G9Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(5),
                    contentType = LGContentType.AUDIO_BOOK,
                    status = BookStatus.UNREAD,
                    duration = 3321,
                    totalOfViews = 900,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 4.8f,
                    totalOfRates = 25,
                    totalOfLikes = 221,
                    publish = "2023-12-18 16:00:07", // LocalDateTime.of(2023, 12, 18, 16, 0,7),
                    classId = 4
                ),
                Book(
                    id = 10,
                    bookUuid = "d24838dd-889a-4710-91d9-c6c3a20c2b0e",
                    bookType = LGBookType.AUDIO_BOOK,
                    name = "F10Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(7),
                    contentType = LGContentType.AUDIO_BOOK,
                    status = BookStatus.FINISH,
                    duration = 86399,
                    totalOfViews = 1234,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 4.7f,
                    totalOfRates = 43,
                    totalOfLikes = 442,
                    publish = "2023-09-12 16:00:07", // LocalDateTime.of(2023, 9, 12, 16, 0,7),
                    classId = 3
                ),
                Book(
                    id = 11,
                    bookUuid = "3d1c22b7-b56a-41a7-a385-a68889725ee7",
                    bookType = LGBookType.PICTURE_BOOK,
                    name = "E11Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(1),
                    contentType = LGContentType.PICTURE_BOOK,
                    status = BookStatus.IN_PROGRESS,
                    duration = 86399,
                    readingTime = 12353,
                    totalOfViews = 2345,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 4.5f,
                    totalOfRates = 32,
                    mostRecentAccess = 1677613906,
                    totalOfLikes = 123,
                    publish = "2023-04-12 16:00:07", // LocalDateTime.of(2023, 4, 12, 16, 0,7),
                    classId = 1
                ),
                Book(
                    id = 12,
                    bookUuid = "3d1c22b7-b56a-41a7-a385-a68889725ee7",
                    bookType = LGBookType.PICTURE_BOOK,
                    name = "D12Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(5),
                    contentType = LGContentType.PICTURE_BOOK,
                    status = BookStatus.IN_PROGRESS,
                    duration = 32221,
                    readingTime = 12353,
                    totalOfViews = 3456,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 2.5f,
                    totalOfRates = 12,
                    mostRecentAccess = 1684340445,
                    totalOfLikes = 423,
                    publish = "2023-06-12 16:00:07", // LocalDateTime.of(2023, 6, 12, 16, 0,7),
                    classId = 3
                ),
                Book(
                    id = 13,
                    bookUuid = "3d1c22b7-b56a-41a7-a385-a68889725ee7",
                    bookType = LGBookType.PICTURE_BOOK,
                    name = "C13Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(9),
                    contentType = LGContentType.PICTURE_BOOK,
                    status = BookStatus.UNREAD,
                    totalOfViews = 4567,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 4.5f,
                    totalOfRates = 321,
                    totalOfLikes = 303,
                    publish = "2023-09-12 16:00:07", // LocalDateTime.of(2023, 9, 12, 16, 0,7),
                    classId = 5
                ),
                Book(
                    id = 14,
                    bookUuid = "3d1c22b7-b56a-41a7-a385-a68889725ee7",
                    bookType = LGBookType.PICTURE_BOOK,
                    name = "B14Mô tả ngắn của sách, tối đa 2 dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(7),
                    contentType = LGContentType.PICTURE_BOOK,
                    status = BookStatus.UNREAD,
                    totalOfViews = 5678,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 3.4f,
                    totalOfRates = 123,
                    totalOfLikes = -1,
                    publish = "2023-12-03 16:00:07", // LocalDateTime.of(2023, 12, 3, 16, 0,7),
                    classId = 4
                ),
                Book(
                    id = 15,
                    bookUuid = "3d1c22b7-b56a-41a7-a385-a68889725ee7",
                    bookType = LGBookType.PICTURE_BOOK,
                    name = "/n/n         A15Mô tả ngắn của sách, tối đa 2/n dòng Mô tả ngắn của sách, tối đa 2 dòng",
                    category = LGCategory.mock().take(3),
                    contentType = LGContentType.PICTURE_BOOK,
                    status = BookStatus.FINISH,
                    totalOfViews = 6789,
                    bestSentence = "Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người. Có một thứ không bao giờ tuân theo nguyên tắc số đông, đó chính là lương tâm con người.",
                    avgRating = 5.0f,
                    totalOfRates = 321,
                    totalOfLikes = 332,
                    publish = "2023-12-05 16:00:07", // LocalDateTime.of(2023, 12, 5, 16, 0,7),
                    classId = 3
                ),
            )
    }
}